name: Policy Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    uses: containerly/.github/.github/workflows/semantic-release.yml@main
    secrets: inherit

  publish-policy:
    needs: release
    if: needs.release.outputs.new-release-published == 'true'
    uses: containerly/.github/.github/workflows/publish-policy-bundle.yml@main
    with:
      version: ${{ needs.release.outputs.new-release-version }}
      policy-path: policy
